# Copyright (C) 2025 Crash Override, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the FSF, either version 3 of the License, or (at your option) any later version.
# See the LICENSE file in the root of this repository for full license text or
# visit: <https://www.gnu.org/licenses/gpl-3.0.html>.

version: "2"
linters:
  settings:
    gosec:
      excludes:
        - G107 # Url provided to HTTP request as taint input
        - G115 # Potential integer overflow when converting between integer types
  enable:
    - errname
    - exhaustive
    - goconst
    - gocritic
    - gosec
    - misspell
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - golines