# This ClusterRole defines permissions for managing Ocular search resources.
# It will be bound to a service account created for a Search invocation.
# While this is a ClusterRole, it will be used with a RoleBinding scoped to the same namespace
# as the Search resource, limiting its effective scope to that namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: search-cluster-role
rules:
  - apiGroups: ["ocular.crashoverride.run"]
    resources: ["pipelines", "searches"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]