apiVersion: ocular.crashoverride.run/v1
kind: Downloader
metadata:
  labels:
    app.kubernetes.io/name: ocular
    app.kubernetes.io/managed-by: kustomize
  name: example-downloader
spec:
  container:
    name: sample-downloader
    image: ghcr.io/bthuilot/git-lost-and-found:v2.1.0
    imagePullPolicy: IfNotPresent
    command: [ /bin/sh, -c ]
    args:
      - |
        git clone $OCULAR_TARGET_IDENTIFIER $OCULAR_TARGET_DIR && \
        cd $OCULAR_TARGET_DIR && \
        git-lost-and-found find --log-format json --repo-path . -k
    volumeMounts:
      - name: ocular-secret-volume
        mountPath: /etc/gitconfig
        subPath: downloader-gitconfig
        readOnly: true
  volumes:
    - name: ocular-secret-volume
      secret:
        secretName: ocular-secret
