apiVersion: ocular.crashoverride.run/v1beta1
kind: Profile
metadata:
  labels:
    app.kubernetes.io/name: ocular
    app.kubernetes.io/managed-by: kustomize
  name: profile-sample
spec:
  containers:
    - name: trufflehog
      image: trufflesecurity/trufflehog:latest
      imagePullPolicy: IfNotPresent
      command: [/bin/sh, -c]
      args: ["trufflehog git file://. -j --no-update > $OCULAR_RESULTS_DIR/trufflehog.json"]
    - name: semgrep
      image: semgrep/semgrep:latest-nonroot
      imagePullPolicy: IfNotPresent
      command: [/bin/sh, -c]
      args: ["semgrep scan --config=auto --json . > $OCULAR_RESULTS_DIR/semgrep.json"]
  artifacts:
    - trufflehog.json
    - semgrep.json
  uploaderRefs:
    - name: uploader-sample
      kind: "Uploader"
      parameters:
        - name: EXAMPLE
          value: example value
    - name: clusteruploader-sample
      kind: "ClusterUploader" # Can be Uploader or ClusterUploader, empty defaults to Uploader
