apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterCrawler
metadata:
  labels:
    app.kubernetes.io/name: ocular
    app.kubernetes.io/managed-by: kustomize
  name: clustercrawler-sample
spec:
  # See `v1beta1_crawler.yaml`
  # for a better example since
  # the 'spec' types are the same
  container:
    image: ubuntu:latest
    command: ['echo']
    args: ['hello', '$(OCULAR_PARAM_NAME)']
  paramters:
    - name: "NAME"
      description: "the name to say hello to"
