apiVersion: ocular.crashoverride.run/v1beta1
kind: Downloader
metadata:
  labels:
    app.kubernetes.io/name: ocular
    app.kubernetes.io/managed-by: kustomize
  name: downloader-sample
spec:
  container:
    name: git
    image: alpine/git:latest
    imagePullPolicy: IfNotPresent
    command: [ /bin/sh, -c ]
    args:
      - |
        GIT_ARGS=""
        if [ -z "$BARE_CLONE" ]; then
          GIT_ARGS="--bare"
        fi
        git clone $GIT_ARGS $OCULAR_TARGET_IDENTIFIER $OCULAR_TARGET_DIR
    volumeMounts:
      - name: downloader-secrets
        mountPath: /etc/ocular/
        readOnly: true
  parameter:
    - name: "BARE_CLONE"
      default: ""
      description: "If set to non-empty value, will use --bare to clone"
  volumes:
    - name: downloader-secrets
      secret:
        optional: true
        secretName: git-downloader-secret
        items:
          - key: gitconfig
            path: gitconfig
