apiVersion: ocular.crashoverride.run/v1beta1
kind: Crawler
metadata:
  labels:
    app.kubernetes.io/name: ocular
    app.kubernetes.io/managed-by: kustomize
  name: crawler-sample
spec:
  container:
    name: example-uploader
    image: bitnami/kubectl:latest
    command: ["/bin/bash", "-c"]
    args:
      - |
         echo "== STARTING SEARCH ${OCULAR_SEARCH_NAME} =="
         echo "PARAMETER (LOG_MSG): ${OCULAR_PARAM_LOG_MSG}"
         echo "WHOAMI: $(kubectl auth whoami)"
         echo "CREATE PIPELINE?: $(kubectl auth can-i create pipelines)"
         echo "CREATE SEARCHES?: $(kubectl auth can-i create searches)"
  parameters:
    - name: "LOG_MSG"
      description: "Log message to print."
      required: true
