# Copyright (C) 2025 Crash Override, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the FSF, either version 3 of the License, or (at your option) any later version.
# See the LICENSE file in the root of this repository for full license text or
# visit: <https://www.gnu.org/licenses/gpl-3.0.html>.

name: cd
on:
  release:
    types: [prereleased, released]

permissions:
  contents: read

env:
  GO_VERSION: 1.24

jobs:
  publish-docker:
    name: publish docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [api-server, extractor]
      fail-fast: false
    permissions:
      packages: write
      contents: read
#      id-token: write
    env:
      TAG: "ghcr.io/${{ github.repository_owner }}/ocular-${{ matrix.image }}:${{ github.ref_name }}"
      LATEST: "ghcr.io/${{ github.repository_owner }}/ocular-${{ matrix.image }}:latest"
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%SZ')"
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Chalk
        uses: crashappsec/setup-chalk-action@cf01792d450e4abb7716a5cd146e4f5e40243a97 # main
      - name: setup qemu
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
      - name: setup buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      - name: docker build
        id: docker-build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          build-args: |
            COMMAND=${{ matrix.image }}
            LDFLAGS=-s -w -X github.com/crashappsec/ocular/internal/config.Version=${{ github.event.release.tag_name }} -X github.com/crashappsec/ocular/internal/config.BuildTime=${{steps.date.outputs.date}} -X github.com/crashappsec/ocular/internal/config.Commit=${{ github.sha }}
          tags: |
            ${{ env.TAG }}
            ${{ (github.event.release.prerelease && '') || env.LATEST }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
