# Copyright (C) 2025-2026 Crash Override, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the FSF, either version 3 of the License, or (at your option) any later version.
# See the LICENSE file in the root of this repository for full license text or
# visit: <https://www.gnu.org/licenses/gpl-3.0.html>.

name: release
on:
  release:
    types: [created, edited]

permissions:
  contents: read

env:
  GO_VERSION: 1.25

  SUFFIX: ${{ github.event.release.prerelease && '-prerelease' || '' }}
  RELEASE_NAME: ${{ github.event.release.name }}

jobs:
  publish-manifest:
    name: publish manfiest
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
      - name: setup go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # ratchet:actions/setup-go@v7.0.0
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: generate manifest
        run: |
          make build-installer OCULAR_VERSION="$RELEASE_NAME$SUFFIX"
          mv dist/install.yaml ocular${SUFFIX}.yaml
      - name: Upload Release Asset
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # ratchet:softprops/action-gh-release@v3.0.3
        with:
          files: ocular${{ env.SUFFIX }}.yaml
  publish-docker:
    name: publish docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [controller, sidecar, scheduler]
    permissions:
      packages: write
      contents: read
      #      id-token: write
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # ratchet:docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Chalk
        uses: crashappsec/setup-chalk-action@0966e85f08bfbabbe3075892881331384819cbc5 # ratchet:crashappsec/setup-chalk-action@v0.0.3
        continue-on-error: true
      - name: setup qemu
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # ratchet:docker/setup-qemu-action@v4.4.0
      - name: setup buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # ratchet:docker/setup-buildx-action@v4.4.1
      - name: docker build
        id: docker-build
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # ratchet:docker/build-push-action@v7.4.0
        with:
          platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
          push: true
          build-args: |
            COMMAND=${{ matrix.image }}
            LDFLAGS=-s -w -X main.version=${{ github.event.release.tag_name }} -X main.buildTime=${{steps.date.outputs.date}} -X main.gitCommit=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ocular-${{ matrix.image }}:${{ env.RELEASE_NAME }}${{ env.SUFFIX }}
            ghcr.io/${{ github.repository_owner }}/ocular-${{ matrix.image }}:latest${{ env.SUFFIX }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
